name: 'Deploy slides to github pages'

on:
  push:
    branches:
      - main
      - master
jobs:
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      # - run: npm i fusuma -D
      # - run: npm ci
      # - run: ls -la
      # - run: npx fusuma build
      - run: ls -la
      - run: pwd
      - run: cd ..
      - run: ls -la
      - run: pwd
      - uses: actions/upload-pages-artifact@v1
        with:
          path: /home/runner/work/ugo4u/ugo4u/dist
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
