name: 'Deploy slides to github pages'

on:
  push:
    branches:
      - main
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      - run: npm i fusuma -D
      - run: npm ci
      - run: ls -la
      - run: npx fusuma build
      - run: ls -la
      - run: pwd
      - run: cd ..
      - run: ls -la
      - run: pwd
      # ./dist/index.htmlにsedを適用する
      - run: sed -i 's/="/="\/ugo4u\//g' ./dist/index.html
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /home/runner/work/ugo4u/ugo4u/dist
